/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe used by the desktop shell on boot.
         */
        get: operations["health_api_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Info
         * @description Application + environment metadata.
         */
        get: operations["info_api_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage
         * @description Disk usage of the data directory.
         */
        get: operations["usage_api_system_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/cpu-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cpu Count
         * @description Number of logical CPUs available for ``n_jobs`` defaults.
         */
        get: operations["cpu_count_api_system_cpu_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/check-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Updates
         * @description Check for app updates by fetching the latest.json manifest.
         *
         *     Returns info about the latest available version and whether an update
         *     is needed.  The user downloads the installer manually via the URL.
         */
        get: operations["check_updates_api_system_check_updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/first-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * First Run Status
         * @description Get first-run wizard state.
         */
        get: operations["first_run_status_api_system_first_run_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/first-run/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete First Run
         * @description Mark the first-run wizard as complete.
         */
        post: operations["complete_first_run_api_system_first_run_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/metric-defs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metric Definitions
         * @description Get metric tooltip definitions for the results table.
         *
         *     Ported from the web app's tooltip dictionary.
         */
        get: operations["metric_definitions_api_system_metric_defs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Dataset
         * @description Upload a CSV file, auto-detect column types, create a Report.
         */
        post: operations["upload_dataset_api_datasets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/upload-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Dataset Path
         * @description Ingest a CSV already on local disk (used by native-window file drop).
         *
         *     The desktop shell runs the API on localhost for the single local user,
         *     so a dropped file is handed over as a path instead of a multipart body.
         */
        post: operations["upload_dataset_path_api_datasets_upload_path_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{report_id}/column-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Column Types
         * @description Re-detect column types from the stored original dataset.
         */
        get: operations["get_column_types_api_datasets__report_id__column_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{report_id}/column-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Column Changes
         * @description Apply user-specified column type changes to the dataset.
         */
        post: operations["column_changes_api_datasets__report_id__column_changes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{report_id}/class-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Class Values
         * @description Get unique class label values for the mapping modal.
         */
        get: operations["get_class_values_api_datasets__report_id__class_values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{report_id}/class-mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Class Mapping
         * @description Create an integer mapping column for a categorical class column.
         */
        post: operations["set_class_mapping_api_datasets__report_id__class_mapping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{report_id}/testset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Testset
         * @description Upload a separate test set CSV.
         */
        post: operations["upload_testset_api_datasets__report_id__testset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{report_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate Dataset
         * @description Duplicate a dataset (copies the file + original_file).
         */
        post: operations["duplicate_dataset_api_datasets__report_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset
         * @description Get details of a single dataset.
         */
        get: operations["get_dataset_api_datasets__report_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Dataset
         * @description Delete a dataset and all its artifacts from storage.
         */
        delete: operations["delete_dataset_api_datasets__report_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description List datasets in DataTables format.
         */
        get: operations["list_datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{report_id}/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Comment
         * @description Update the comments on a dataset.
         */
        patch: operations["update_comment_api_datasets__report_id__comment_patch"];
        trace?: never;
    };
    "/api/datasets/{report_id}/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Parameters
         * @description Get the previous training parameters for a dataset (for rerun).
         */
        get: operations["get_parameters_api_datasets__report_id__parameters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Jobs
         * @description List all jobs.
         */
        get: operations["get_jobs_api_jobs_get"];
        put?: never;
        /**
         * Start Training
         * @description Start a training job.  Parses options and enqueues.
         */
        post: operations["start_training_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description Get a single job's status.
         */
        get: operations["get_job_status_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancel a running or queued job.
         */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Events
         * @description SSE stream of job progress updates.
         *
         *     The frontend subscribes to this endpoint to get live progress.
         */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/ml-options/supervised": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ml Options Supervised
         * @description Get supervised ML options for the Prepare page.
         */
        get: operations["ml_options_supervised_api_jobs_ml_options_supervised_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/ml-options/unsupervised": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ml Options Unsupervised
         * @description Get unsupervised ML options for the Prepare page.
         */
        get: operations["ml_options_unsupervised_api_jobs_ml_options_unsupervised_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recover Stale Jobs
         * @description Mark stale running jobs as failed (called on app startup).
         */
        post: operations["recover_stale_jobs_api_jobs_recover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Results
         * @description Get the results table (report.csv) for a trained dataset.
         */
        get: operations["get_results_api_results__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/viz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Visualizations
         * @description List all visualization PNGs for a dataset.
         */
        get: operations["list_visualizations_api_results__report_id__viz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/viz/{viz_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Visualization
         * @description Serve a single visualization PNG.
         */
        get: operations["get_visualization_api_results__report_id__viz__viz_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/shap-rows/{model}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shap Rows
         * @description Get the per-row SHAP CSV for a model.
         */
        get: operations["get_shap_rows_api_results__report_id__shap_rows__model__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/shap-row-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shap Row Graph Endpoint
         * @description Generate a per-row SHAP impact bar chart PNG.
         */
        get: operations["get_shap_row_graph_endpoint_api_results__report_id__shap_row_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/retest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retest Models
         * @description Re-test saved models on a new testset.
         */
        post: operations["retest_models_api_results__report_id__retest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/output-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Output Log
         * @description Get the training output log.
         */
        get: operations["get_output_log_api_results__report_id__output_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Artifact
         * @description Download any artifact from storage.
         */
        get: operations["download_artifact_api_results__report_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/prepare-params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prepare Params
         * @description Get previous training parameters for rerun-with-same-params.
         */
        get: operations["get_prepare_params_api_results__report_id__prepare_params_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List all training runs (current + archived) for a dataset.
         */
        get: operations["list_runs_api_results__report_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/runs/{job_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Results
         * @description Get results table for a specific (archived or current) run.
         */
        get: operations["get_run_results_api_results__report_id__runs__job_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/runs/{job_id}/output-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Output Log
         * @description Get output log for a specific (archived or current) run.
         */
        get: operations["get_run_output_log_api_results__report_id__runs__job_id__output_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/runs/{job_id}/viz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Run Visualizations
         * @description List visualizations for a specific (archived or current) run.
         */
        get: operations["list_run_visualizations_api_results__report_id__runs__job_id__viz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{report_id}/runs/{job_id}/viz/{viz_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Visualization
         * @description Serve a visualization PNG for a specific (archived or current) run.
         */
        get: operations["get_run_visualization_api_results__report_id__runs__job_id__viz__viz_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Addons Endpoint
         * @description List all available add-ons with installation status.
         */
        get: operations["list_addons_endpoint_api_addons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addons/{name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Addon Status
         * @description Get detailed status for a single add-on.
         */
        get: operations["addon_status_api_addons__name__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addons/{name}/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Install Addon Endpoint
         * @description Start an add-on installation (runs in background — poll install-status).
         */
        post: operations["install_addon_endpoint_api_addons__name__install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addons/{name}/install-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Install Status
         * @description Poll the live status of an in-progress add-on installation.
         */
        get: operations["install_status_api_addons__name__install_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addons/{name}/uninstall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Uninstall Addon Endpoint
         * @description Uninstall an add-on.
         */
        post: operations["uninstall_addon_endpoint_api_addons__name__uninstall_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addons/modules/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Modules
         * @description Check which optional ML modules are currently importable.
         */
        get: operations["check_modules_api_addons_modules_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddonInfo
         * @description Info about a single add-on.
         */
        AddonInfo: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Description */
            description: string;
            /** Pip Deps */
            pip_deps?: string[];
            /**
             * Size Estimate Mb
             * @default 0
             */
            size_estimate_mb: number;
            /**
             * Min App Version
             * @default 1.0.0
             */
            min_app_version: string;
            /** Provides */
            provides?: string[];
            /**
             * Installed
             * @default false
             */
            installed: boolean;
        };
        /**
         * AddonInstallResponse
         * @description Response from install/uninstall.
         */
        AddonInstallResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /**
         * AddonListResponse
         * @description List of all add-ons.
         */
        AddonListResponse: {
            /** Addons */
            addons?: components["schemas"]["AddonInfo"][];
        };
        /**
         * AddonStatusResponse
         * @description Detailed status for a single add-on.
         */
        AddonStatusResponse: {
            /** Name */
            name: string;
            /** Installed */
            installed: boolean;
            /** Version */
            version: string;
            /** Description */
            description: string;
            /** Size Estimate Mb */
            size_estimate_mb: number;
            /** Modules Available */
            modules_available?: {
                [key: string]: boolean;
            };
            /**
             * All Modules Available
             * @default false
             */
            all_modules_available: boolean;
        };
        /** Body_retest_models_api_results__report_id__retest_post */
        Body_retest_models_api_results__report_id__retest_post: {
            request: components["schemas"]["RetestRequest"];
            /** Testset */
            testset: string;
        };
        /** Body_upload_dataset_api_datasets_upload_post */
        Body_upload_dataset_api_datasets_upload_post: {
            /** File */
            file: string;
        };
        /** Body_upload_testset_api_datasets__report_id__testset_post */
        Body_upload_testset_api_datasets__report_id__testset_post: {
            /** File */
            file: string;
        };
        /**
         * ClassMappingRequest
         * @description POST /api/datasets/{id}/class-mapping.
         */
        ClassMappingRequest: {
            /** Class Column */
            class_column: string;
            /** Mapping */
            mapping: {
                [key: string]: number;
            };
        };
        /**
         * ClassValuesResponse
         * @description GET /api/datasets/{id}/class-values.
         */
        ClassValuesResponse: {
            /** Success */
            success: boolean;
            /** Class Values */
            class_values?: string[];
        };
        /**
         * ColumnChangeRequest
         * @description A single column change from the column preview modal.
         */
        ColumnChangeRequest: {
            /** Column */
            column: string;
            /**
             * Data Type
             * @default string
             */
            data_type: string;
            /**
             * Checked
             * @default true
             */
            checked: boolean;
            /**
             * Missing
             * @default
             */
            missing: string;
            /**
             * Fill Value
             * @default
             */
            fill_value: string;
            /**
             * Is Class
             * @default false
             */
            is_class: boolean;
        };
        /**
         * ColumnChangesRequest
         * @description POST /api/datasets/{id}/column-changes.
         */
        ColumnChangesRequest: {
            /** Data Types */
            data_types?: components["schemas"]["ColumnChangeRequest"][];
        };
        /**
         * ColumnChangesResponse
         * @description Response for column-changes endpoint.
         */
        ColumnChangesResponse: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data Types */
            data_types?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ColumnTypesResponse
         * @description GET /api/datasets/{id}/column-types.
         */
        ColumnTypesResponse: {
            /** Success */
            success: boolean;
            /** Data Types */
            data_types?: {
                [key: string]: string;
            };
            /** Missing Values */
            missing_values?: {
                [key: string]: boolean;
            };
        };
        /**
         * CommentUpdate
         * @description PATCH /api/datasets/{id}/comment.
         */
        CommentUpdate: {
            /** Comments */
            comments: string;
        };
        /**
         * DatasetListResponse
         * @description GET /api/datasets — DataTable-style response.
         */
        DatasetListResponse: {
            /**
             * Draw
             * @default 0
             */
            draw: number;
            /**
             * Recordstotal
             * @default 0
             */
            recordsTotal: number;
            /**
             * Recordsfiltered
             * @default 0
             */
            recordsFiltered: number;
            /** Data */
            data?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DatasetPathUploadRequest
         * @description POST /api/datasets/upload-path — ingest a file already on local disk.
         */
        DatasetPathUploadRequest: {
            /** Path */
            path: string;
        };
        /**
         * DatasetUploadResponse
         * @description POST /api/datasets/upload.
         */
        DatasetUploadResponse: {
            /** Success */
            success: boolean;
            /** Report Id */
            report_id?: string | null;
            /** Filename */
            filename?: string | null;
            /** Data Types */
            data_types?: {
                [key: string]: string;
            };
            /** Missing Values */
            missing_values?: {
                [key: string]: boolean;
            };
            /** Message */
            message?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobListResponse
         * @description List of jobs.
         */
        JobListResponse: {
            /** Jobs */
            jobs?: components["schemas"]["JobResponse"][];
        };
        /**
         * JobResponse
         * @description A single job's status.
         */
        JobResponse: {
            /** Id */
            id: string;
            /** Report Uuid */
            report_uuid: string;
            /** State */
            state: string;
            /** Args */
            args?: {
                [key: string]: unknown;
            } | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Progress Total
             * @default 0
             */
            progress_total: number;
            /** Progress Message */
            progress_message?: string | null;
            /** Error */
            error?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * OutputLogResponse
         * @description GET /api/results/{report_id}/output-log.
         */
        OutputLogResponse: {
            /** Success */
            success: boolean;
            /**
             * Log
             * @default
             */
            log: string;
        };
        /**
         * ParametersResponse
         * @description GET /api/datasets/{id}/parameters — previous training args.
         */
        ParametersResponse: {
            /** Success */
            success: boolean;
            /** Args */
            args?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * PrepareParamsResponse
         * @description GET /api/datasets/{id}/prepare-params — for rerun with same params.
         */
        PrepareParamsResponse: {
            /** Success */
            success: boolean;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /** Class Column */
            class_column?: string | null;
        };
        /**
         * ResultsResponse
         * @description GET /api/results/{report_id} — metrics table + results JSON.
         */
        ResultsResponse: {
            /** Success */
            success: boolean;
            /** Report Csv */
            report_csv?: {
                [key: string]: unknown;
            }[];
            /** Columns */
            columns?: string[];
            /** Results Json */
            results_json?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RetestRequest
         * @description POST /api/results/{report_id}/retest.
         */
        RetestRequest: {
            /** Model Names */
            model_names: string[];
            /**
             * Class Column
             * @default class
             */
            class_column: string;
        };
        /**
         * RetestResponse
         * @description Response for retest.
         */
        RetestResponse: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * RunInfo
         * @description A single training run (current or archived).
         */
        RunInfo: {
            /** Job Id */
            job_id: string;
            /** State */
            state: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
            /** Args */
            args?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RunListResponse
         * @description GET /api/results/{report_id}/runs.
         */
        RunListResponse: {
            /** Success */
            success: boolean;
            /** Runs */
            runs?: components["schemas"]["RunInfo"][];
        };
        /**
         * ShapRowsResponse
         * @description GET /api/results/{report_id}/shap-rows/{model}.
         */
        ShapRowsResponse: {
            /** Success */
            success: boolean;
            /** Rows */
            rows?: {
                [key: string]: unknown;
            }[];
            /** Columns */
            columns?: string[];
        };
        /**
         * SuccessResponse
         * @description Generic success/error response.
         */
        SuccessResponse: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * TrainRequest
         * @description POST /api/jobs — start training.
         */
        TrainRequest: {
            /** Report Id */
            report_id: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VizListResponse
         * @description GET /api/results/{report_id}/viz — list of visualization names.
         */
        VizListResponse: {
            /** Success */
            success: boolean;
            /** Visualizations */
            visualizations?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    info_api_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    usage_api_system_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    cpu_count_api_system_cpu_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    check_updates_api_system_check_updates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    first_run_status_api_system_first_run_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    complete_first_run_api_system_first_run_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metric_definitions_api_system_metric_defs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upload_dataset_api_datasets_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_datasets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_path_api_datasets_upload_path_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetPathUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_column_types_api_datasets__report_id__column_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnTypesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    column_changes_api_datasets__report_id__column_changes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColumnChangesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnChangesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_class_values_api_datasets__report_id__class_values_get: {
        parameters: {
            query: {
                /** @description Name of the class column */
                class_column: string;
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassValuesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_class_mapping_api_datasets__report_id__class_mapping_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassMappingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_testset_api_datasets__report_id__testset_post: {
        parameters: {
            query?: {
                class_column?: string;
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_testset_api_datasets__report_id__testset_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_dataset_api_datasets__report_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_api_datasets__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_api_datasets__report_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_datasets_get: {
        parameters: {
            query?: {
                start?: number;
                length?: number;
                search?: string;
                order_by?: string;
                order_dir?: string;
                draw?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_comment_api_datasets__report_id__comment_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_parameters_api_datasets__report_id__parameters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParametersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
        };
    };
    start_training_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ml_options_supervised_api_jobs_ml_options_supervised_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ml_options_unsupervised_api_jobs_ml_options_unsupervised_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recover_stale_jobs_api_jobs_recover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    get_results_api_results__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_visualizations_api_results__report_id__viz_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VizListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visualization_api_results__report_id__viz__viz_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
                viz_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shap_rows_api_results__report_id__shap_rows__model__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
                model: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShapRowsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shap_row_graph_endpoint_api_results__report_id__shap_row_graph_get: {
        parameters: {
            query: {
                model: string;
                row_num: number;
                train_test?: string;
                class_column?: string;
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retest_models_api_results__report_id__retest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_retest_models_api_results__report_id__retest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_output_log_api_results__report_id__output_log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_api_results__report_id__download_get: {
        parameters: {
            query: {
                /** @description Artifact key suffix (e.g. 'file', 'results', 'randomforest_model.joblib') */
                suffix: string;
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prepare_params_api_results__report_id__prepare_params_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrepareParamsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_results__report_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_results_api_results__report_id__runs__job_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_output_log_api_results__report_id__runs__job_id__output_log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_run_visualizations_api_results__report_id__runs__job_id__viz_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VizListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_visualization_api_results__report_id__runs__job_id__viz__viz_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
                job_id: string;
                viz_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_addons_endpoint_api_addons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddonListResponse"];
                };
            };
        };
    };
    addon_status_api_addons__name__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddonStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    install_addon_endpoint_api_addons__name__install_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddonInstallResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    install_status_api_addons__name__install_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uninstall_addon_endpoint_api_addons__name__uninstall_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddonInstallResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_modules_api_addons_modules_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
